title: UAIbot
description: Multi-language web-based simulator for interactive robotics learning and research in full 3D
theme: just-the-docs

url: https://uaibot.github.io/

aux_links:
  GitHub repositories: https://github.com/UAIbot

color_scheme: foo.scss

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/favicon.png"

math: katex

